language: node_js
node_js:
- 12
install: npm install
script: npm test
env:
  global:
  - secure: AlOYvAkiq6A7T5RGf5C87HW+NLZNcAH6Ef5grTaGj51RY4G5eyMt0SgsyPvQ5wTFR1g9bdoXGxCYpgDPII7128UxBwPXLIcufvqCm8MwDVe++zCiUmo0c0MZA54Okjfb4cKjfG60uTvozgP8qid0ejuGxOnb1/6IAgjCV1T634jtnRopwC3Y9F4PT86Tlv5bYReGE8fRSuWicWWlc4rvdP1F5vz6JeYeRMyT/33e2uhkm4tW2uYgB5oxqrdlWGefIHSN+oNj6UY7t2wUJTRIwu4LlbouG7Lx0TQj4Qs5gFBR6rouixM+oVrO8RztQd89hL3YLBcT82zKBlQeDCB1dndACdwEIM3znGEPCnx4S5qEbJVodNhKeypepyLZBPJhUmgmiiHK1uHbWHlQsd0ylD+scxFGb02TxGtXaxfX1dauhIwdyx2hYG97fpvzSJ2/MIXlDqMWGvapLL9Al/rnrw3dr6TB631DwL9EtlhXhYhG7S+sA2eY4p9ul8Gbj8jGJTCmqsRmSbCwKNb/my8vIy4H/rLRu576py9nAJu3DB8eSb5BksXEap9A7f0KVoSc0XW0fqn/O+UDrhwFQe0MeL2ZdtFVrphkTLfapof6+Bm5VldveY259+e7gCe4Ngn8hbM+kPud73dibyiIZmILk6pIFLKVRwZO9XVNhl6l0CI=
